server:
  port: 5999
  appRoot: "/bucky"

  # If the following values are set, bucky will run as https and parse the key and cert files
  # Place the key and cert files in the BuckyServer directory with server.coffee

  # https:
  #   options:
  #     key: "key.pem"
  #     cert: "cert.pem"

statsd:
  host: 'localhost'
  port: 8125

opentsdb:
  host: 'localhost'
  port: 4242

influxdb:
  host: 'localhost'
  port: 8086
  database: 'bucky'
  username: 'root'
  password: 'root'
  use_udp: false
  retentionPolicy: 'default'
  # All version other than '0.9' will default to '0.8'
  version: '0.9'


modules:
  # The modules just get require'd in, so they don't have to be in the Bucky project.
  app:
    - ./modules/trustProxy
    - ./modules/auth
    # This should be last so that collectors get installed as the last handlers in the chain
    - ./modules/collectors

  collectors:
  # Uncomment the modules that you'd like to use
    - ./modules/collectionLogger
    # - ./modules/statsd
    # - ./modules/openTSDB
    # - ./modules/influxdb
