server:
  port: 5999
  appRoot: "/bucky"

statsd:
  host: 'localhost'
  port: 8125

opentsdb:
  host: 'localhost'
  port: 4242

modules:
  # The modules just get require'd in, so they don't have to be in the Bucky project.
  app:
    - ./modules/trustProxy
    - ./modules/auth
    # This should be last so that collectors get installed as the last handlers in the chain
    - ./modules/collectors

  collectors:
    - ./modules/collectionLogger
    - ./modules/statsd
    - ./modules/openTSDB
