server:
  port: 5999
  appRoot: "/bucky"
  # If https options are set then bucky will also listen on https
  # https:
    # port: 5599
    # See full list of options at: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
    # options:
      # key: "ssl/key.pem"
      # cert: "ssl/cert.pem"
  # If the following is set to true then bucky server will not run in http mode
  # httpsOnly: true

statsd:
  host: 'localhost'
  port: 8125

opentsdb:
  host: 'localhost'
  port: 4242

influxdb:
  host: 'localhost'
  port: 8086
  database: 'bucky'
  username: 'root'
  password: 'root'
  use_udp: false
  retentionPolicy: 'default'
  # All version other than '0.9' will default to '0.8'
  version: '0.9'


modules:
  # The modules just get require'd in, so they don't have to be in the Bucky project.
  app:
    - ./modules/trustProxy
    - ./modules/auth
    # This should be last so that collectors get installed as the last handlers in the chain
    - ./modules/collectors

  collectors:
  # Uncomment the modules that you'd like to use
    - ./modules/collectionLogger
    # - ./modules/statsd
    # - ./modules/openTSDB
    # - ./modules/influxdb
