server:
  port: 5999
  appRoot: "bucky"

statsd:
  host: 'localhost'
  port: 8125

opentsdb:
  host: 'localhost'
  port: 5555

modules:
  app:
    - ./modules/sentry
    - ./modules/trustProxy
    - ./modules/auth
    # This should be last so that collectors get installed as the last handlers in the chain
    - ./modules/collectors

  collectors:
    - ./modules/collectionLogger
    - ./modules/collectedCounter
    - ./modules/statsd
    - ./modules/openTSDB
