server:
  port: 5999
  appRoot: "/bucky"

statsd:
  host: 'localhost'
  port: 8125

opentsdb:
  host: 'localhost'
  port: 4242

influxdb:
  host: 'localhost'
  port: 8086
  database: 'bucky'
  username: 'root'
  password: 'root'
  use_udp: false
  retentionPolicy: 'default'
  # Acceptable version are: '0.8' and '0.9'
  version: '0.9'

onlyAcceptWhitelistedKeys: false

modules:
  # The modules just get require'd in, so they don't have to be in the Bucky project.
  app:
    - ./modules/trustProxy
    - ./modules/auth
    # This should be last so that collectors get installed as the last handlers in the chain
    - ./modules/collectors

  collectors:
  # Uncomment the modules that you'd like to use
    # - ./modules/collectionLogger
    # - ./modules/statsd
    # - ./modules/openTSDB
    # - ./modules/influxdb

  whitelistedKeys:
  # The example below are timing metrics that Bucky includes by default. You will need to whitelist these if you use the default configuration of Bucky and enable whitelisting by setting useWhitelistedKeys to true
    # - file.page.navigationStart
    # - file.page.unloadEventStart
    # - file.page.unloadEventEnd
    # - file.page.fetchStart
    # - file.page.domainLookupStart
    # - file.page.domainLookupEnd
    # - file.page.connectStart
    # - file.page.connectEnd
    # - file.page.requestStart
    # - file.page.responseStart
    # - file.page.responseEnd
    # - file.page.domLoading
    # - file.page.domInteractive
    # - file.page.domContentLoadedEventStart
    # - file.page.toJSON
    # - time.to.click.dont.click.button
    # - dont.click.button.clicks
